---
abstract: 'Make text table from database.'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Teng-Plugin-TextTable
no_index:
  directory:
    - inc
provides:
  Teng::Plugin::TextTable:
    file: lib/Teng/Plugin/TextTable.pm
    version: 0.01
requires:
  List::Util: 0
  Teng: 0
  Text::SimpleTable: 0
  perl: 5.010001
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
